import { SHADOW_7, SHADOW_5, SHADOW_0, SHADOW_1 } from './../../../Utils/Values/shadows';
import { ScaledSheet } from 'react-native-size-matters';
import { SHADOW_2, SHADOW_3, SIZES } from '../../../Utils/Values';

const styleScaled = (Color: any) =>
{
    return ScaledSheet.create({
        bgColor: {
            backgroundColor: Color.BG,
            // backgroundColor: 'pink',
            flex: 1,
        },
        container: {
            // flexDirection: "row",
            // justifyContent: "space-between",
            flex: 1,
            alignItems: 'center',
            width: '100%',
            paddingVertical: '8@ms',
            paddingHorizontal: '12@ms',
            // borderRadius: "40@ms",
            // ...SHADOW_3,
            alignSelf: 'center',
            zIndex: 1,
            marginTop: (SIZES.HEIGHT_STATUSBAR ?? 0) + 10,
            position: 'relative',
        },
        cardBoxResult: {
            width: SIZES.WIDTH_WINDOW - 25,
            // borderWidth: 2,
            borderColor: Color.ON_SURFACE_VARIANT,
            marginVertical: 10,
            paddingVertical: 5,
            paddingHorizontal: 10,
            borderRadius: 10,
            backgroundColor: Color.BG,
            ...SHADOW_5,
            alignItems: 'center',
            flexDirection: 'row',
            // justifyContent: 'center',
        },
        cardBoxResult2: {
            width: SIZES.WIDTH_WINDOW - 25,
            // borderWidth: 2,
            borderColor: Color.ON_SURFACE_VARIANT,
            marginVertical: 10,
            // paddingVertical: 5,
            // paddingHorizontal: 10,
            // borderBottomRadius: 10,
            borderBottomLeftRadius: 10,
            borderBottomRightRadius: 10,
            backgroundColor: Color.BG,
            ...SHADOW_5,
            alignItems: 'center',
            // flexDirection: 'row',
            // justifyContent: 'center',
        },
        left: {
            width: (SIZES.WIDTH_WINDOW - 25) / 2 - 10,
            // backgroundColor: 'red',
        },
        right: {
            width: (SIZES.WIDTH_WINDOW - 25) / 2 - 10,
            // backgroundColor: 'pink',
            // textAlign: 'center',
        },
        subTitle2: {
            fontSize: '20@ms0.5',
            // fontWeight: 'light',
            fontWeight: 'bold',
            color: Color.TITLE_TXT,
            // marginBottom: 1.5,
            marginVertical: 5,
            // marginTop: '10@vs',
            letterSpacing: 0.5,
            // width: '100%',
            // textAlign: 'center',
            textTransform: 'capitalize',
        },
        subTitle: {
            fontSize: '19@ms0.5',
            // fontWeight: 'light',
            fontWeight: 'bold',
            color: Color.TITLE_TXT,
            // marginBottom: 1.5,
            marginVertical: 5,
            // marginTop: '10@vs',
            letterSpacing: 0.5,
            // width: '100%',
            // textAlign: 'center',
            textTransform: 'capitalize',
        },
    });
};
export default styleScaled;
