import { ScaledSheet } from 'react-native-size-matters';
import { SHADOW_3 } from '../../Utils/Values';

const styleScaled = (props) =>
{
    return ScaledSheet.create({
        container: {
            flex: 1,
            paddingBottom: 80,
        },
        viewContent: {
            flex: 1,
            alignItems: 'center',
            marginTop: 110,
            marginBottom: 100,
        },
        viewRank: {
            backgroundColor: props.BG,
            width: '90%',
            borderRadius: 10,
            ...SHADOW_3,
            minHeight: 300,
        },
        row: {
            width: '100%',
            height: 50,
            flexDirection: 'row',
        },
        viewHr: {
            alignItems: 'center',
        },
        hr: {
            width: '80%',
            height: 1,
            backgroundColor: '#c4c4c4',
            opacity: 0.4,
        },
        viewLeft: {
            width: '20%',
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
        },
        viewMid: {
            width: '60%',
            alignItems: 'center',
            flexDirection: 'row',
        },
        viewRight: {
            width: '20%',
            justifyContent: 'center',
            alignItems: 'center',
        },
        Stt: {
            fontSize: 20,
            fontWeight: 'bold',
            fontStyle: 'italic',
            color: props.TXT_COUNT,
        },
        nameRow: {
            color: props.TXT_COUNT,
        },
        Point: {
            fontSize: 18,
            fontWeight: 'bold',
            color: '#FF8A8A',
        },
        avatar: {
            width: 30,
            height: 30,
            backgroundColor: '#FF8A8A',
            borderRadius: 999,
            marginRight: 10,
        },
        second: {
            width: 100,
            height: 100,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            backgroundColor: '#FEA36D',
            alignItems: 'center',
            paddingHorizontal: 5,
            ...SHADOW_3,
        },
        first: {
            width: 110,
            height: 105,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            backgroundColor: '#FED65D',
            alignItems: 'center',
            paddingHorizontal: 5,
            ...SHADOW_3,
        },
        textYou: {
            color: 'white',
            textAlign: 'center',
            fontWeight: 'bold',
            fontSize: 13,
        },
        third: {
            width: 95,
            height: 95,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            backgroundColor: '#FEC881',
            alignItems: 'center',
            paddingHorizontal: 5,
            ...SHADOW_3,
        },
        viewTop: {
            flexDirection: 'row',
            width: '100%',
            justifyContent: 'space-between',
            paddingHorizontal: 40,
            alignItems: 'flex-end',
        },
        name: {
            color: 'white',
            textAlign: 'center',
            marginTop: 30,
            marginBottom: 3,
        },
        point2: {
            color: 'white',
            textAlign: 'center',
            fontWeight: 'bold',
            fontSize: 18,
        },
        Stt2: {
            fontSize: 20,
            fontWeight: 'bold',
            fontStyle: 'italic',
            backgroundColor: 'white',
            width: 50,
            borderRadius: 20,
            textAlign: 'center',
            marginBottom: 5,
            position: 'absolute',
            ...SHADOW_3,
        },
        secondAvatar: {
            width: 80,
            height: 80,
            backgroundColor: '#FEA26F',
            borderRadius: 999,
            position: 'absolute',
            top: -65,
            ...SHADOW_3,
        },
        firstAvatar: {
            width: 90,
            height: 90,
            backgroundColor: '#FEA26F',
            borderRadius: 999,
            position: 'absolute',
            top: -75,
            ...SHADOW_3,
        },
        thirdAvatar: {
            width: 70,
            height: 70,
            backgroundColor: '#FEA26F',
            borderRadius: 999,
            position: 'absolute',
            top: -55,
            ...SHADOW_3,
        },
        btn: {
            paddingHorizontal: 15,
            paddingVertical: 5,
            backgroundColor: props.BG,
            borderRadius: 20,
            ...SHADOW_3,
            flexDirection: 'row',
        },
        btn2: {
            paddingHorizontal: 15,
            paddingVertical: 5,
            backgroundColor: '#fe746f',
            borderRadius: 20,
            ...SHADOW_3,
            flexDirection: 'row',
        },
        viewBtn: {
            flexDirection: 'row',
            width: '100%',
            justifyContent: 'center',
            marginTop: 20,
        },
        textBtn: {
            fontSize: 16,
            color: props.TXT_COUNT,
        },
        textBtn2: {
            color: 'white',
            fontSize: 16,
        },
    });
};
export default styleScaled;
